### ISSUE TITLE
Parallelism!

### ISSUE THREAD

**Issue by aleozlx** [aleozlx/playbook-rs#16]
* DAG workflow with a fork-join pattern
* Parameter grid (yaml tag annotation would actually help here)

**Comment by aleozlx** [comment]
Here's an idea for the parameter grid

```yaml
steps:
- action: sys_states
  # storage TBD, a local mutexed retry file?; if any thing crashes, we can rerun failed tasks by keeping track of states.
- action: sys_fork
  resources:
    cuda_devices: ["0", "1", "2", "3"]
  grid:
  - param1: [10, 20, 40, 80, 160]
  - param2: [0.03, 0.01, 0.003, 0.001]
````
